# -*- coding: utf-8 -*-
"""scoutproject.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17-yS1ihRSYXBOa98oGtbgBYEFJA06pou
"""

import streamlit as st
import pandas as pd
import os
import streamlit_authenticator as stauth

# ======================
# ARQUIVOS
# ======================
USERS_FILE = "usuarios.csv"
DB_FILE = "projetos.csv"
IMG_DIR = "fotos"

# Garante a pasta de fotos
os.makedirs(IMG_DIR, exist_ok=True)

# Cria arquivo de usuários se não existir
if not os.path.exists(USERS_FILE):
    df_users = pd.DataFrame(columns=["username", "nome", "senha_hash"])
    df_users.to_csv(USERS_FILE, index=False)

# Cria arquivo de projetos se não existir
if not os.path.exists(DB_FILE):
    df_proj = pd.DataFrame(columns=["Nome", "Autor", "Categoria", "Descrição", "Foto"])
    df_proj.to_csv(DB_FILE, index=False)

# ======================
# FUNÇÕES DE USUÁRIO
# ======================
def cadastrar_usuario(username, nome, senha):
    global usuarios   # tem que vir no início da função

    if username in usuarios['username'].values:
        return False, "Usuário já existe!"

    # Gera o hash da senha
    senha_hash = stauth.Hasher([senha]).generate()
    senha_hash = senha_hash[0]  # garante que pegamos apenas a string

    # Adiciona o usuário ao "banco"
    novo_usuario = pd.DataFrame([{
        'username': username,
        'nome': nome,
        'senha': senha_hash
    }])

    usuarios = pd.concat([usuarios, novo_usuario], ignore_index=True)
    usuarios.to_csv("usuarios.csv", index=False)

    return True, "Usuário cadastrado com sucesso!"


def autenticar_usuario(username, senha):
    df_users = pd.read_csv(USERS_FILE)
    if username not in df_users["username"].values:
        return False, None

    senha_hash = df_users.loc[df_users["username"] == username, "senha_hash"].values[0]
    if stauth.Hasher([senha]).check([senha], [senha_hash])[0]:
        nome = df_users.loc[df_users["username"] == username, "nome"].values[0]
        return True, nome
    else:
        return False, None

# ======================
# INTERFACE
# ======================
st.set_page_config(page_title="Banco de Projetos Escoteiros", layout="wide")
st.title("📚 Banco de Projetos Escoteiros")

menu = st.sidebar.radio("Menu", ["Login", "Registrar", "Consultar Projetos"])

# LOGIN
if menu == "Login":
    st.subheader("Login")
    username = st.text_input("Usuário")
    senha = st.text_input("Senha", type="password")

    if st.button("Entrar"):
        ok, nome = autenticar_usuario(username, senha)
        if ok:
            st.success(f"Bem-vindo, {nome}!")

            # Menu interno
            escolha = st.radio("O que deseja fazer?", ["Cadastrar Projeto", "Consultar Projetos"])

            if escolha == "Cadastrar Projeto":
                st.header("Cadastrar novo projeto escoteiro")

                nome_proj = st.text_input("Nome do projeto")
                categoria = st.selectbox("Categoria", ["Meio Ambiente", "Comunidade", "Cultura", "Educação", "Outro"])
                descricao = st.text_area("Descrição do projeto")
                foto = st.file_uploader("Adicionar foto do projeto", type=["jpg", "jpeg", "png"])

                if st.button("Salvar projeto"):
                    foto_path = ""
                    if foto is not None:
                        foto_path = os.path.join(IMG_DIR, f"{nome_proj}_{foto.name}")
                        with open(foto_path, "wb") as f:
                            f.write(foto.getbuffer())

                    novo = pd.DataFrame([[nome_proj, nome, categoria, descricao, foto_path]],
                                        columns=["Nome", "Autor", "Categoria", "Descrição", "Foto"])
                    df = pd.read_csv(DB_FILE)
                    df = pd.concat([df, novo], ignore_index=True)
                    df.to_csv(DB_FILE, index=False)
                    st.success("Projeto salvo com sucesso!")

            elif escolha == "Consultar Projetos":
                st.header("Banco de Projetos Escoteiros")
                df = pd.read_csv(DB_FILE)

                filtro_categoria = st.selectbox("Filtrar por categoria", ["Todas"] + df["Categoria"].unique().tolist())
                if filtro_categoria != "Todas":
                    df = df[df["Categoria"] == filtro_categoria]

                if len(df) == 0:
                    st.info("Nenhum projeto encontrado.")
                else:
                    cols = st.columns(3)
                    for i, (_, row) in enumerate(df.iterrows()):
                        col = cols[i % 3]
                        with col:
                            st.markdown(f"### {row['Nome']}")
                            st.write(f"👤 {row['Autor']}")
                            if row["Foto"] and os.path.exists(row["Foto"]):
                                st.image(row["Foto"], use_container_width=True)
                            st.caption(f"📂 {row['Categoria']}")
                            with st.expander("Descrição"):
                                st.write(row["Descrição"])
                            st.markdown("---")

        else:
            st.error("Usuário ou senha incorretos")

# REGISTRO
elif menu == "Registrar":
    st.subheader("Registrar novo usuário")
    new_username = st.text_input("Usuário")
    new_nome = st.text_input("Nome completo")
    new_senha = st.text_input("Senha", type="password")

    if st.button("Cadastrar"):
        ok, msg = cadastrar_usuario(new_username, new_nome, new_senha)
        if ok:
            st.success(msg)
        else:
            st.error(msg)

# CONSULTAR SEM LOGIN (somente leitura)
elif menu == "Consultar Projetos":
    st.header("Banco de Projetos Escoteiros")
    df = pd.read_csv(DB_FILE)
    if len(df) == 0:
        st.info("Nenhum projeto cadastrado ainda.")
    else:
        filtro_categoria = st.selectbox("Filtrar por categoria", ["Todas"] + df["Categoria"].unique().tolist())
        if filtro_categoria != "Todas":
            df = df[df["Categoria"] == filtro_categoria]

        cols = st.columns(3)
        for i, (_, row) in enumerate(df.iterrows()):
            col = cols[i % 3]
            with col:
                st.markdown(f"### {row['Nome']}")
                st.write(f"👤 {row['Autor']}")
                if row["Foto"] and os.path.exists(row["Foto"]):
                    st.image(row["Foto"], use_container_width=True)
                st.caption(f"📂 {row['Categoria']}")
                with st.expander("Descrição"):
                    st.write(row["Descrição"])
                st.markdown("---")
