# -*- coding: utf-8 -*-
"""scoutproject.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17-yS1ihRSYXBOa98oGtbgBYEFJA06pou
"""

import streamlit as st
import pandas as pd
import os
import streamlit_authenticator as stauth
from PIL import Image

# ==============================
# Carregar ou criar o banco de usuários
# ==============================
try:
    usuarios = pd.read_csv("usuarios.csv")
except FileNotFoundError:
    usuarios = pd.DataFrame(columns=["username", "nome", "senha"])
    usuarios.to_csv("usuarios.csv", index=False)

# ==============================
# Carregar ou criar o banco de projetos
# ==============================
try:
    projetos = pd.read_csv("projetos.csv")
except FileNotFoundError:
    projetos = pd.DataFrame(columns=["usuario", "nome_projeto", "descricao", "area", "foto"])
    projetos.to_csv("projetos.csv", index=False)

# ==============================
# Função de cadastro de usuário
# ==============================
def cadastrar_usuario(username, nome, senha):
    global usuarios

    if username in usuarios['username'].values:
        return False, "Usuário já existe!"

    # Gera hash da senha
    senha_hash = stauth.Hasher([senha]).generate()[0]

    novo_usuario = pd.DataFrame([{
        "username": username,
        "nome": nome,
        "senha": senha_hash
    }])

    usuarios = pd.concat([usuarios, novo_usuario], ignore_index=True)
    usuarios.to_csv("usuarios.csv", index=False)

    return True, "Usuário cadastrado com sucesso!"

# ==============================
# Função de autenticação
# ==============================
def autenticar():
    global usuarios
    if usuarios.empty:
        return None, False, "Nenhum usuário cadastrado."

    credentials = {
        "usernames": {
            row["username"]: {
                "name": row["nome"],
                "password": row["senha"]
            } for _, row in usuarios.iterrows()
        }
    }

    authenticator = stauth.Authenticate(
        credentials,
        "scout_app",
        "abcdef",
        cookie_expiry_days=1
    )

    nome, auth_status, username = authenticator.login("Login", "main")
    return authenticator, nome, auth_status, username

# ==============================
# Função de cadastro de projeto
# ==============================
def cadastrar_projeto(usuario, nome_projeto, descricao, area, foto):
    global projetos

    caminho_foto = ""
    if foto:
        caminho_foto = os.path.join("fotos", foto.name)
        os.makedirs("fotos", exist_ok=True)
        with open(caminho_foto, "wb") as f:
            f.write(foto.getbuffer())

    novo_projeto = pd.DataFrame([{
        "usuario": usuario,
        "nome_projeto": nome_projeto,
        "descricao": descricao,
        "area": area,
        "foto": caminho_foto
    }])

    projetos = pd.concat([projetos, novo_projeto], ignore_index=True)
    projetos.to_csv("projetos.csv", index=False)

    return True, "Projeto cadastrado com sucesso!"

# ==============================
# Streamlit Interface
# ==============================
st.sidebar.title("Menu")
pagina = st.sidebar.radio("Navegar", ["Login", "Cadastro de Usuário", "Projetos"])

if pagina == "Cadastro de Usuário":
    st.title("Cadastro de Usuário")
    new_username = st.text_input("Usuário")
    new_nome = st.text_input("Nome")
    new_senha = st.text_input("Senha", type="password")

    if st.button("Cadastrar"):
        ok, msg = cadastrar_usuario(new_username, new_nome, new_senha)
        st.success(msg) if ok else st.error(msg)

elif pagina == "Login":
    st.title("Login")
    authenticator, nome, auth_status, username = autenticar()

    if auth_status:
        st.success(f"Bem-vindo, {nome}!")
        authenticator.logout("Logout", "sidebar")

elif pagina == "Projetos":
    st.title("Projetos Escoteiros")
    authenticator, nome, auth_status, username = autenticar()

    if auth_status:
        st.subheader("Cadastrar Novo Projeto")
        nome_projeto = st.text_input("Nome do Projeto")
        descricao = st.text_area("Descrição")
        area = st.selectbox("Área", ["Ambiental", "Comunitária", "Tecnologia", "Educação", "Outro"])
        foto = st.file_uploader("Foto do Projeto", type=["jpg", "jpeg", "png"])

        if st.button("Salvar Projeto"):
            ok, msg = cadastrar_projeto(username, nome_projeto, descricao, area, foto)
            st.success(msg)

        st.subheader("Projetos Existentes")
        for _, row in projetos.iterrows():
            st.markdown(f"### {row['nome_projeto']}")
            st.write(f"👤 {row['usuario']} | 📂 {row['area']}")
            st.write(row["descricao"])
            if row["foto"] and os.path.exists(row["foto"]):
                st.image(row["foto"], width=300)
            st.markdown("---")

    else:
        st.warning("Faça login para acessar os projetos.")
